package com.ecoskiller.mcp.its.handlers;

import com.ecoskiller.mcp.its.security.SecurityValidator;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.List;
import java.util.logging.Logger;

/**
 * TimestampHandler
 *
 * Implements:
 *   get_timestamp_proof  — Immutable timestamp + content_hash + minio_etag (IP evidence)
 *   list_idea_versions   — All version records from innovation.idea_versions
 *   get_idea_ownership   — Canonical ownership record from innovation.ideas
 *
 * Per ITS spec §5.1 and §6.1:
 *   - submitted_at is IMMUTABLE after creation (PostgreSQL NOT NULL, no UPDATE allowed)
 *   - content_hash is the SHA-256 from the canonical JSON at submission time
 *   - minio_etag is the MD5 of the uploaded MinIO object (secondary integrity check)
 *   - version history is append-only (innovation.idea_versions: no UPDATE/DELETE)
 */
public class TimestampHandler {

    private static final Logger LOG = Logger.getLogger(TimestampHandler.class.getName());

    private final ObjectMapper mapper = new ObjectMapper();
    private final SecurityValidator validator;

    public TimestampHandler(SecurityValidator sv) {
        this.validator = sv;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Tool: get_timestamp_proof
    // ─────────────────────────────────────────────────────────────────────────

    public Object getTimestampProof(JsonNode args) {
        String ideaId   = require(args, "idea_id");
        String tenantId = require(args, "tenant_id");
        int    version  = args.path("version").asInt(0); // 0 = latest

        String key      = SubmissionHandler.storeKey(tenantId, ideaId);
        ObjectNode idea = SubmissionHandler.ideaStore.get(key);

        ObjectNode resp = mapper.createObjectNode();
        resp.put("idea_id",   ideaId);
        resp.put("tenant_id", tenantId);

        if (idea == null) {
            resp.put("found",   false);
            resp.put("message", "No idea found. In production: SELECT from innovation.ideas WHERE " +
                "idea_id=? AND tenant_id=? (RLS enforced).");
            addProductionNote(resp);
            return resp;
        }

        // Determine target version
        List<ObjectNode> versions = SubmissionHandler.versionStore.getOrDefault(key, List.of());
        ObjectNode targetVer = versions.isEmpty() ? null
            : (version > 0 && version <= versions.size())
              ? versions.get(version - 1)
              : versions.get(versions.size() - 1); // latest

        resp.put("found", true);

        // Core immutable proof fields (per ITS spec §6.1)
        ObjectNode proof = resp.putObject("timestamp_proof");
        proof.put("idea_id",          ideaId);
        proof.put("tenant_id",        tenantId);
        proof.put("candidate_id",     idea.path("candidate_id").asText());
        proof.put("version",          targetVer != null ? targetVer.path("version_number").asInt() : 1);
        proof.put("submitted_at",     idea.path("submitted_at").asText()); // IMMUTABLE — v1 anchor
        proof.put("content_hash",     targetVer != null
            ? targetVer.path("content_hash").asText()
            : idea.path("content_hash").asText());
        proof.put("content_hash_algorithm", "SHA-256");
        proof.put("minio_object_key", targetVer != null
            ? targetVer.path("minio_object_key").asText()
            : idea.path("minio_object_key").asText());
        proof.put("minio_etag",       targetVer != null
            ? targetVer.path("minio_etag").asText()
            : idea.path("minio_etag").asText());
        proof.put("visibility_level", idea.path("visibility_level").asText());
        proof.put("idea_category",    idea.path("idea_category").asText());

        // Legal/IP note (per ITS spec §9.1)
        ObjectNode legal = resp.putObject("ip_evidence_note");
        legal.put("submitted_at_authority",
            "Authoritative UTC timestamp generated by PostgreSQL transaction clock " +
            "(NOT client-supplied). Monotonic, tamper-resistant.");
        legal.put("content_hash_purpose",
            "SHA-256 provides mathematically binding proof of idea content at submitted_at. " +
            "Any modification produces a completely different hash (avalanche effect).");
        legal.put("dual_integrity",
            "content_hash (SHA-256) + minio_etag (MD5) provide two independent verification pathways.");
        legal.put("legal_defensibility",
            "This record constitutes proof of prior art: the idea existed in this exact form " +
            "on the platform at submitted_at UTC.");
        legal.put("patent_note",
            "Candidates should file patent BEFORE submitting to Ecoskiller to preserve patent rights.");
        legal.put("verify_endpoint",
            "Use verify_idea_integrity to confirm content integrity at any time.");

        LOG.info("get_timestamp_proof: idea_id=" + ideaId + " version=" + version);
        return resp;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Tool: list_idea_versions
    // ─────────────────────────────────────────────────────────────────────────

    public Object listIdeaVersions(JsonNode args) {
        String ideaId   = require(args, "idea_id");
        String tenantId = require(args, "tenant_id");

        String key      = SubmissionHandler.storeKey(tenantId, ideaId);
        ObjectNode idea = SubmissionHandler.ideaStore.get(key);

        ObjectNode resp = mapper.createObjectNode();
        resp.put("idea_id",   ideaId);
        resp.put("tenant_id", tenantId);

        if (idea == null) {
            resp.put("found",          false);
            resp.put("version_count",  0);
            resp.put("message",
                "No idea found. In production: SELECT * FROM innovation.idea_versions " +
                "WHERE idea_id=? ORDER BY version_number ASC (append-only table).");
            return resp;
        }

        List<ObjectNode> versions = SubmissionHandler.versionStore.getOrDefault(key, List.of());

        resp.put("found",         true);
        resp.put("version_count", versions.size());
        resp.put("current_status", idea.path("status").asText());
        resp.put("latest_version", versions.isEmpty() ? 1 : versions.get(versions.size()-1).path("version_number").asInt());

        ArrayNode versArr = resp.putArray("versions");
        for (ObjectNode v : versions) {
            ObjectNode entry = versArr.addObject();
            entry.put("version_number",  v.path("version_number").asInt());
            entry.put("version_id",      v.path("version_id").asText());
            entry.put("content_hash",    v.path("content_hash").asText());
            entry.put("submitted_at",    v.path("submitted_at").asText());
            entry.put("minio_object_key",v.path("minio_object_key").asText());
            entry.put("minio_etag",      v.path("minio_etag").asText());
            if (v.has("revision_reason"))
                entry.put("revision_reason", v.path("revision_reason").asText());
        }

        ObjectNode note = resp.putObject("schema_note");
        note.put("table", "innovation.idea_versions");
        note.put("immutability", "Append-only: no UPDATE or DELETE permitted on this table");
        note.put("rls", "Row-Level Security enforced: tenant_id must match session context");

        LOG.info("list_idea_versions: idea_id=" + ideaId + " versions=" + versions.size());
        return resp;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Tool: get_idea_ownership
    // ─────────────────────────────────────────────────────────────────────────

    public Object getIdeaOwnership(JsonNode args) {
        String ideaId   = require(args, "idea_id");
        String tenantId = require(args, "tenant_id");

        String key      = SubmissionHandler.storeKey(tenantId, ideaId);
        ObjectNode idea = SubmissionHandler.ideaStore.get(key);

        ObjectNode resp = mapper.createObjectNode();
        resp.put("idea_id",   ideaId);
        resp.put("tenant_id", tenantId);

        if (idea == null) {
            resp.put("found",   false);
            resp.put("message",
                "No ownership record found. In production: SELECT * FROM innovation.ideas " +
                "WHERE idea_id=? AND tenant_id=? (PostgreSQL RLS enforced).");
            return resp;
        }

        resp.put("found", true);

        ObjectNode ownership = resp.putObject("ownership_record");
        ownership.put("idea_id",          idea.path("idea_id").asText());
        ownership.put("tenant_id",        idea.path("tenant_id").asText());
        ownership.put("candidate_id",     idea.path("candidate_id").asText()); // primary owner
        ownership.put("submitted_at",     idea.path("submitted_at").asText()); // immutable v1 anchor
        ownership.put("content_hash",     idea.path("content_hash").asText()); // v1 SHA-256
        ownership.put("visibility_level", idea.path("visibility_level").asText());
        ownership.put("status",           idea.path("status").asText());
        ownership.put("idea_category",    idea.path("idea_category").asText());
        ownership.put("current_version",  idea.path("version").asInt());
        ownership.put("minio_object_key", idea.path("minio_object_key").asText());

        ObjectNode licensing = resp.putObject("licensing_eligibility");
        String status = idea.path("status").asText();
        boolean eligible = "VERIFIED_ORIGINAL".equals(status);
        licensing.put("eligible_for_licensing", eligible);
        licensing.put("reason", eligible
            ? "Idea passed similarity check (VERIFIED_ORIGINAL). Eligible for licensing-contract-service (Module XIII)."
            : "Status is " + status + ". Only VERIFIED_ORIGINAL ideas may enter licensing workflows.");
        if (eligible) {
            licensing.put("licensing_note",
                "licensing-contract-service will apply MinIO Object Lock (WORM governance mode) " +
                "to this object upon contract initiation, preventing deletion for the contract period.");
        }

        ObjectNode rls = resp.putObject("security_note");
        rls.put("rls_enforced", "PostgreSQL Row-Level Security: SELECT restricted to matching tenant_id");
        rls.put("pgcrypto", "idea_title encrypted at rest for PRIVATE visibility (AES-256-CBC)");
        rls.put("immutable_fields", "submitted_at, content_hash (v1) cannot be updated after creation");

        LOG.info("get_idea_ownership: idea_id=" + ideaId);
        return resp;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void addProductionNote(ObjectNode resp) {
        ObjectNode note = resp.putObject("production_note");
        note.put("table",     "innovation.ideas");
        note.put("rls",       "Row-Level Security enforced by tenant_id");
        note.put("immutable", "submitted_at and content_hash are immutable after INSERT");
    }

    private String require(JsonNode args, String field) {
        JsonNode n = args.get(field);
        if (n == null || n.isNull() || n.asText().isBlank())
            throw new IllegalArgumentException("Missing required field: " + field);
        return n.asText().trim();
    }
}
